apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dns-spoofer
  namespace: default
spec:
  template:
    metadata:
      labels:
        name: dns-spoofer
    spec:
      containers:
      - name: dns-spoofer
        image: rhysemmas/kube-dnsspoof
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
