apiVersion: v1
kind: Pod
metadata:
  name: dns-spoofer
  namespace: default
spec:
  affinity:
    podAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
      - labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - kube-dns
        topologyKey: failure-domain.beta.kubernetes.io/zone
        namespaces: 
        - kube-system
  containers:
  - name: dns-spoofer
    image: rhysemmas/kube-dnsspoof
